// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: storagesite.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageSiteInfoService_GetStorageSiteById_FullMethodName   = "/storagesite.StorageSiteInfoService/GetStorageSiteById"
	StorageSiteInfoService_GetStorageSiteByNo_FullMethodName   = "/storagesite.StorageSiteInfoService/GetStorageSiteByNo"
	StorageSiteInfoService_GetStorageSiteByName_FullMethodName = "/storagesite.StorageSiteInfoService/GetStorageSiteByName"
	StorageSiteInfoService_GetStorageSiteByIp_FullMethodName   = "/storagesite.StorageSiteInfoService/GetStorageSiteByIp"
)

// StorageSiteInfoServiceClient is the client API for StorageSiteInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 存储站点信息服务
type StorageSiteInfoServiceClient interface {
	// 根据存储站点ID查询信息
	GetStorageSiteById(ctx context.Context, in *GetStorageSiteByIdReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error)
	// 根据存储站点编号查询信息
	GetStorageSiteByNo(ctx context.Context, in *GetStorageSiteByNoReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error)
	// 根据存储站点名称查询信息
	GetStorageSiteByName(ctx context.Context, in *GetStorageSiteByNameReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error)
	// 根据存储站点IP查询信息
	GetStorageSiteByIp(ctx context.Context, in *GetStorageSiteByIpReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error)
}

type storageSiteInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageSiteInfoServiceClient(cc grpc.ClientConnInterface) StorageSiteInfoServiceClient {
	return &storageSiteInfoServiceClient{cc}
}

func (c *storageSiteInfoServiceClient) GetStorageSiteById(ctx context.Context, in *GetStorageSiteByIdReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSiteInfoReply)
	err := c.cc.Invoke(ctx, StorageSiteInfoService_GetStorageSiteById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageSiteInfoServiceClient) GetStorageSiteByNo(ctx context.Context, in *GetStorageSiteByNoReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSiteInfoReply)
	err := c.cc.Invoke(ctx, StorageSiteInfoService_GetStorageSiteByNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageSiteInfoServiceClient) GetStorageSiteByName(ctx context.Context, in *GetStorageSiteByNameReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSiteInfoReply)
	err := c.cc.Invoke(ctx, StorageSiteInfoService_GetStorageSiteByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageSiteInfoServiceClient) GetStorageSiteByIp(ctx context.Context, in *GetStorageSiteByIpReq, opts ...grpc.CallOption) (*StorageSiteInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSiteInfoReply)
	err := c.cc.Invoke(ctx, StorageSiteInfoService_GetStorageSiteByIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageSiteInfoServiceServer is the server API for StorageSiteInfoService service.
// All implementations must embed UnimplementedStorageSiteInfoServiceServer
// for forward compatibility.
//
// 存储站点信息服务
type StorageSiteInfoServiceServer interface {
	// 根据存储站点ID查询信息
	GetStorageSiteById(context.Context, *GetStorageSiteByIdReq) (*StorageSiteInfoReply, error)
	// 根据存储站点编号查询信息
	GetStorageSiteByNo(context.Context, *GetStorageSiteByNoReq) (*StorageSiteInfoReply, error)
	// 根据存储站点名称查询信息
	GetStorageSiteByName(context.Context, *GetStorageSiteByNameReq) (*StorageSiteInfoReply, error)
	// 根据存储站点IP查询信息
	GetStorageSiteByIp(context.Context, *GetStorageSiteByIpReq) (*StorageSiteInfoReply, error)
	mustEmbedUnimplementedStorageSiteInfoServiceServer()
}

// UnimplementedStorageSiteInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageSiteInfoServiceServer struct{}

func (UnimplementedStorageSiteInfoServiceServer) GetStorageSiteById(context.Context, *GetStorageSiteByIdReq) (*StorageSiteInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageSiteById not implemented")
}
func (UnimplementedStorageSiteInfoServiceServer) GetStorageSiteByNo(context.Context, *GetStorageSiteByNoReq) (*StorageSiteInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageSiteByNo not implemented")
}
func (UnimplementedStorageSiteInfoServiceServer) GetStorageSiteByName(context.Context, *GetStorageSiteByNameReq) (*StorageSiteInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageSiteByName not implemented")
}
func (UnimplementedStorageSiteInfoServiceServer) GetStorageSiteByIp(context.Context, *GetStorageSiteByIpReq) (*StorageSiteInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageSiteByIp not implemented")
}
func (UnimplementedStorageSiteInfoServiceServer) mustEmbedUnimplementedStorageSiteInfoServiceServer() {
}
func (UnimplementedStorageSiteInfoServiceServer) testEmbeddedByValue() {}

// UnsafeStorageSiteInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageSiteInfoServiceServer will
// result in compilation errors.
type UnsafeStorageSiteInfoServiceServer interface {
	mustEmbedUnimplementedStorageSiteInfoServiceServer()
}

func RegisterStorageSiteInfoServiceServer(s grpc.ServiceRegistrar, srv StorageSiteInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageSiteInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageSiteInfoService_ServiceDesc, srv)
}

func _StorageSiteInfoService_GetStorageSiteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageSiteByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageSiteInfoService_GetStorageSiteById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteById(ctx, req.(*GetStorageSiteByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageSiteInfoService_GetStorageSiteByNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageSiteByNoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageSiteInfoService_GetStorageSiteByNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByNo(ctx, req.(*GetStorageSiteByNoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageSiteInfoService_GetStorageSiteByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageSiteByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageSiteInfoService_GetStorageSiteByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByName(ctx, req.(*GetStorageSiteByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageSiteInfoService_GetStorageSiteByIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageSiteByIpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageSiteInfoService_GetStorageSiteByIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageSiteInfoServiceServer).GetStorageSiteByIp(ctx, req.(*GetStorageSiteByIpReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageSiteInfoService_ServiceDesc is the grpc.ServiceDesc for StorageSiteInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageSiteInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storagesite.StorageSiteInfoService",
	HandlerType: (*StorageSiteInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStorageSiteById",
			Handler:    _StorageSiteInfoService_GetStorageSiteById_Handler,
		},
		{
			MethodName: "GetStorageSiteByNo",
			Handler:    _StorageSiteInfoService_GetStorageSiteByNo_Handler,
		},
		{
			MethodName: "GetStorageSiteByName",
			Handler:    _StorageSiteInfoService_GetStorageSiteByName_Handler,
		},
		{
			MethodName: "GetStorageSiteByIp",
			Handler:    _StorageSiteInfoService_GetStorageSiteByIp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storagesite.proto",
}
