// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: storagesite.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息定义
type GetStorageSiteByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                             // 存储站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageSiteByIdReq) Reset() {
	*x = GetStorageSiteByIdReq{}
	mi := &file_storagesite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageSiteByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageSiteByIdReq) ProtoMessage() {}

func (x *GetStorageSiteByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_storagesite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageSiteByIdReq.ProtoReflect.Descriptor instead.
func (*GetStorageSiteByIdReq) Descriptor() ([]byte, []int) {
	return file_storagesite_proto_rawDescGZIP(), []int{0}
}

func (x *GetStorageSiteByIdReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetStorageSiteByIdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStorageSiteByNoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                 // 租户ID
	StorageSiteNo string                 `protobuf:"bytes,2,opt,name=storage_site_no,json=storageSiteNo,proto3" json:"storage_site_no,omitempty"` // 存储站点编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageSiteByNoReq) Reset() {
	*x = GetStorageSiteByNoReq{}
	mi := &file_storagesite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageSiteByNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageSiteByNoReq) ProtoMessage() {}

func (x *GetStorageSiteByNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_storagesite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageSiteByNoReq.ProtoReflect.Descriptor instead.
func (*GetStorageSiteByNoReq) Descriptor() ([]byte, []int) {
	return file_storagesite_proto_rawDescGZIP(), []int{1}
}

func (x *GetStorageSiteByNoReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetStorageSiteByNoReq) GetStorageSiteNo() string {
	if x != nil {
		return x.StorageSiteNo
	}
	return ""
}

type GetStorageSiteByNameReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                       // 租户ID
	StorageSiteName string                 `protobuf:"bytes,2,opt,name=storage_site_name,json=storageSiteName,proto3" json:"storage_site_name,omitempty"` // 存储站点名称
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStorageSiteByNameReq) Reset() {
	*x = GetStorageSiteByNameReq{}
	mi := &file_storagesite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageSiteByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageSiteByNameReq) ProtoMessage() {}

func (x *GetStorageSiteByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_storagesite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageSiteByNameReq.ProtoReflect.Descriptor instead.
func (*GetStorageSiteByNameReq) Descriptor() ([]byte, []int) {
	return file_storagesite_proto_rawDescGZIP(), []int{2}
}

func (x *GetStorageSiteByNameReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetStorageSiteByNameReq) GetStorageSiteName() string {
	if x != nil {
		return x.StorageSiteName
	}
	return ""
}

type GetStorageSiteByIpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                 // 租户ID
	StorageSiteIp string                 `protobuf:"bytes,2,opt,name=storage_site_ip,json=storageSiteIp,proto3" json:"storage_site_ip,omitempty"` // 存储站点IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageSiteByIpReq) Reset() {
	*x = GetStorageSiteByIpReq{}
	mi := &file_storagesite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageSiteByIpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageSiteByIpReq) ProtoMessage() {}

func (x *GetStorageSiteByIpReq) ProtoReflect() protoreflect.Message {
	mi := &file_storagesite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageSiteByIpReq.ProtoReflect.Descriptor instead.
func (*GetStorageSiteByIpReq) Descriptor() ([]byte, []int) {
	return file_storagesite_proto_rawDescGZIP(), []int{3}
}

func (x *GetStorageSiteByIpReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetStorageSiteByIpReq) GetStorageSiteIp() string {
	if x != nil {
		return x.StorageSiteIp
	}
	return ""
}

// 响应消息定义 - 只暴露核心字段
type StorageSiteInfoReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                   // 主键ID
	StorageSiteNo   string                 `protobuf:"bytes,2,opt,name=storage_site_no,json=storageSiteNo,proto3" json:"storage_site_no,omitempty"`       // 存储站点编号
	StorageSiteName string                 `protobuf:"bytes,3,opt,name=storage_site_name,json=storageSiteName,proto3" json:"storage_site_name,omitempty"` // 存储站点名称
	StorageSiteIp   string                 `protobuf:"bytes,4,opt,name=storage_site_ip,json=storageSiteIp,proto3" json:"storage_site_ip,omitempty"`       // IP地址
	StorageSiteUrl  string                 `protobuf:"bytes,5,opt,name=storage_site_url,json=storageSiteUrl,proto3" json:"storage_site_url,omitempty"`    // 播放地址(HTTP)
	OpenStatus      int32                  `protobuf:"varint,6,opt,name=open_status,json=openStatus,proto3" json:"open_status,omitempty"`                 // 启用状态(0禁用/1启用)
	AuthKey         string                 `protobuf:"bytes,7,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`                           // 认证密钥
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageSiteInfoReply) Reset() {
	*x = StorageSiteInfoReply{}
	mi := &file_storagesite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSiteInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSiteInfoReply) ProtoMessage() {}

func (x *StorageSiteInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_storagesite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSiteInfoReply.ProtoReflect.Descriptor instead.
func (*StorageSiteInfoReply) Descriptor() ([]byte, []int) {
	return file_storagesite_proto_rawDescGZIP(), []int{4}
}

func (x *StorageSiteInfoReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageSiteInfoReply) GetStorageSiteNo() string {
	if x != nil {
		return x.StorageSiteNo
	}
	return ""
}

func (x *StorageSiteInfoReply) GetStorageSiteName() string {
	if x != nil {
		return x.StorageSiteName
	}
	return ""
}

func (x *StorageSiteInfoReply) GetStorageSiteIp() string {
	if x != nil {
		return x.StorageSiteIp
	}
	return ""
}

func (x *StorageSiteInfoReply) GetStorageSiteUrl() string {
	if x != nil {
		return x.StorageSiteUrl
	}
	return ""
}

func (x *StorageSiteInfoReply) GetOpenStatus() int32 {
	if x != nil {
		return x.OpenStatus
	}
	return 0
}

func (x *StorageSiteInfoReply) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

var File_storagesite_proto protoreflect.FileDescriptor

const file_storagesite_proto_rawDesc = "" +
	"\n" +
	"\x11storagesite.proto\x12\vstoragesite\"D\n" +
	"\x15GetStorageSiteByIdReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\\\n" +
	"\x15GetStorageSiteByNoReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12&\n" +
	"\x0fstorage_site_no\x18\x02 \x01(\tR\rstorageSiteNo\"b\n" +
	"\x17GetStorageSiteByNameReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12*\n" +
	"\x11storage_site_name\x18\x02 \x01(\tR\x0fstorageSiteName\"\\\n" +
	"\x15GetStorageSiteByIpReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12&\n" +
	"\x0fstorage_site_ip\x18\x02 \x01(\tR\rstorageSiteIp\"\x88\x02\n" +
	"\x14StorageSiteInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12&\n" +
	"\x0fstorage_site_no\x18\x02 \x01(\tR\rstorageSiteNo\x12*\n" +
	"\x11storage_site_name\x18\x03 \x01(\tR\x0fstorageSiteName\x12&\n" +
	"\x0fstorage_site_ip\x18\x04 \x01(\tR\rstorageSiteIp\x12(\n" +
	"\x10storage_site_url\x18\x05 \x01(\tR\x0estorageSiteUrl\x12\x1f\n" +
	"\vopen_status\x18\x06 \x01(\x05R\n" +
	"openStatus\x12\x19\n" +
	"\bauth_key\x18\a \x01(\tR\aauthKey2\x98\x03\n" +
	"\x16StorageSiteInfoService\x12]\n" +
	"\x12GetStorageSiteById\x12\".storagesite.GetStorageSiteByIdReq\x1a!.storagesite.StorageSiteInfoReply\"\x00\x12]\n" +
	"\x12GetStorageSiteByNo\x12\".storagesite.GetStorageSiteByNoReq\x1a!.storagesite.StorageSiteInfoReply\"\x00\x12a\n" +
	"\x14GetStorageSiteByName\x12$.storagesite.GetStorageSiteByNameReq\x1a!.storagesite.StorageSiteInfoReply\"\x00\x12]\n" +
	"\x12GetStorageSiteByIp\x12\".storagesite.GetStorageSiteByIpReq\x1a!.storagesite.StorageSiteInfoReply\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_storagesite_proto_rawDescOnce sync.Once
	file_storagesite_proto_rawDescData []byte
)

func file_storagesite_proto_rawDescGZIP() []byte {
	file_storagesite_proto_rawDescOnce.Do(func() {
		file_storagesite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagesite_proto_rawDesc), len(file_storagesite_proto_rawDesc)))
	})
	return file_storagesite_proto_rawDescData
}

var file_storagesite_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_storagesite_proto_goTypes = []any{
	(*GetStorageSiteByIdReq)(nil),   // 0: storagesite.GetStorageSiteByIdReq
	(*GetStorageSiteByNoReq)(nil),   // 1: storagesite.GetStorageSiteByNoReq
	(*GetStorageSiteByNameReq)(nil), // 2: storagesite.GetStorageSiteByNameReq
	(*GetStorageSiteByIpReq)(nil),   // 3: storagesite.GetStorageSiteByIpReq
	(*StorageSiteInfoReply)(nil),    // 4: storagesite.StorageSiteInfoReply
}
var file_storagesite_proto_depIdxs = []int32{
	0, // 0: storagesite.StorageSiteInfoService.GetStorageSiteById:input_type -> storagesite.GetStorageSiteByIdReq
	1, // 1: storagesite.StorageSiteInfoService.GetStorageSiteByNo:input_type -> storagesite.GetStorageSiteByNoReq
	2, // 2: storagesite.StorageSiteInfoService.GetStorageSiteByName:input_type -> storagesite.GetStorageSiteByNameReq
	3, // 3: storagesite.StorageSiteInfoService.GetStorageSiteByIp:input_type -> storagesite.GetStorageSiteByIpReq
	4, // 4: storagesite.StorageSiteInfoService.GetStorageSiteById:output_type -> storagesite.StorageSiteInfoReply
	4, // 5: storagesite.StorageSiteInfoService.GetStorageSiteByNo:output_type -> storagesite.StorageSiteInfoReply
	4, // 6: storagesite.StorageSiteInfoService.GetStorageSiteByName:output_type -> storagesite.StorageSiteInfoReply
	4, // 7: storagesite.StorageSiteInfoService.GetStorageSiteByIp:output_type -> storagesite.StorageSiteInfoReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storagesite_proto_init() }
func file_storagesite_proto_init() {
	if File_storagesite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagesite_proto_rawDesc), len(file_storagesite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storagesite_proto_goTypes,
		DependencyIndexes: file_storagesite_proto_depIdxs,
		MessageInfos:      file_storagesite_proto_msgTypes,
	}.Build()
	File_storagesite_proto = out.File
	file_storagesite_proto_goTypes = nil
	file_storagesite_proto_depIdxs = nil
}
