// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: casbin_policy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPoliciesRequest 查询策略请求
type GetPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 租户 ID（必填），遵循所有现有 gRPC 接口的约定：tenant_id 始终为第一个字段
	TenantId      int32 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesRequest) Reset() {
	*x = GetPoliciesRequest{}
	mi := &file_casbin_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesRequest) ProtoMessage() {}

func (x *GetPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesRequest.ProtoReflect.Descriptor instead.
func (*GetPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_casbin_policy_proto_rawDescGZIP(), []int{0}
}

func (x *GetPoliciesRequest) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

// GetPoliciesResponse 查询策略响应
type GetPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*CasbinPolicyEntry   `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"` // 策略规则列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesResponse) Reset() {
	*x = GetPoliciesResponse{}
	mi := &file_casbin_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesResponse) ProtoMessage() {}

func (x *GetPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesResponse.ProtoReflect.Descriptor instead.
func (*GetPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_casbin_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GetPoliciesResponse) GetPolicies() []*CasbinPolicyEntry {
	if x != nil {
		return x.Policies
	}
	return nil
}

// CasbinPolicyEntry 单条 Casbin 策略规则
type CasbinPolicyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PType         string                 `protobuf:"bytes,1,opt,name=p_type,json=pType,proto3" json:"p_type,omitempty"` // 策略类型: "p"(策略) 或 "g"(角色继承)
	V0            string                 `protobuf:"bytes,2,opt,name=v0,proto3" json:"v0,omitempty"`                    // 通常为 sub (角色名)
	V1            string                 `protobuf:"bytes,3,opt,name=v1,proto3" json:"v1,omitempty"`                    // 通常为 obj (资源路径)
	V2            string                 `protobuf:"bytes,4,opt,name=v2,proto3" json:"v2,omitempty"`                    // 通常为 act (HTTP 方法)
	V3            string                 `protobuf:"bytes,5,opt,name=v3,proto3" json:"v3,omitempty"`                    // 可选扩展字段
	V4            string                 `protobuf:"bytes,6,opt,name=v4,proto3" json:"v4,omitempty"`                    // 可选扩展字段
	V5            string                 `protobuf:"bytes,7,opt,name=v5,proto3" json:"v5,omitempty"`                    // 可选扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasbinPolicyEntry) Reset() {
	*x = CasbinPolicyEntry{}
	mi := &file_casbin_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasbinPolicyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasbinPolicyEntry) ProtoMessage() {}

func (x *CasbinPolicyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_casbin_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasbinPolicyEntry.ProtoReflect.Descriptor instead.
func (*CasbinPolicyEntry) Descriptor() ([]byte, []int) {
	return file_casbin_policy_proto_rawDescGZIP(), []int{2}
}

func (x *CasbinPolicyEntry) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV0() string {
	if x != nil {
		return x.V0
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV1() string {
	if x != nil {
		return x.V1
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV2() string {
	if x != nil {
		return x.V2
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV3() string {
	if x != nil {
		return x.V3
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV4() string {
	if x != nil {
		return x.V4
	}
	return ""
}

func (x *CasbinPolicyEntry) GetV5() string {
	if x != nil {
		return x.V5
	}
	return ""
}

var File_casbin_policy_proto protoreflect.FileDescriptor

const file_casbin_policy_proto_rawDesc = "" +
	"\n" +
	"\x13casbin_policy.proto\x12\x06casbin\"1\n" +
	"\x12GetPoliciesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\"L\n" +
	"\x13GetPoliciesResponse\x125\n" +
	"\bpolicies\x18\x01 \x03(\v2\x19.casbin.CasbinPolicyEntryR\bpolicies\"\x8a\x01\n" +
	"\x11CasbinPolicyEntry\x12\x15\n" +
	"\x06p_type\x18\x01 \x01(\tR\x05pType\x12\x0e\n" +
	"\x02v0\x18\x02 \x01(\tR\x02v0\x12\x0e\n" +
	"\x02v1\x18\x03 \x01(\tR\x02v1\x12\x0e\n" +
	"\x02v2\x18\x04 \x01(\tR\x02v2\x12\x0e\n" +
	"\x02v3\x18\x05 \x01(\tR\x02v3\x12\x0e\n" +
	"\x02v4\x18\x06 \x01(\tR\x02v4\x12\x0e\n" +
	"\x02v5\x18\a \x01(\tR\x02v52_\n" +
	"\x13CasbinPolicyService\x12H\n" +
	"\vGetPolicies\x12\x1a.casbin.GetPoliciesRequest\x1a\x1b.casbin.GetPoliciesResponse\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_casbin_policy_proto_rawDescOnce sync.Once
	file_casbin_policy_proto_rawDescData []byte
)

func file_casbin_policy_proto_rawDescGZIP() []byte {
	file_casbin_policy_proto_rawDescOnce.Do(func() {
		file_casbin_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_casbin_policy_proto_rawDesc), len(file_casbin_policy_proto_rawDesc)))
	})
	return file_casbin_policy_proto_rawDescData
}

var file_casbin_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_casbin_policy_proto_goTypes = []any{
	(*GetPoliciesRequest)(nil),  // 0: casbin.GetPoliciesRequest
	(*GetPoliciesResponse)(nil), // 1: casbin.GetPoliciesResponse
	(*CasbinPolicyEntry)(nil),   // 2: casbin.CasbinPolicyEntry
}
var file_casbin_policy_proto_depIdxs = []int32{
	2, // 0: casbin.GetPoliciesResponse.policies:type_name -> casbin.CasbinPolicyEntry
	0, // 1: casbin.CasbinPolicyService.GetPolicies:input_type -> casbin.GetPoliciesRequest
	1, // 2: casbin.CasbinPolicyService.GetPolicies:output_type -> casbin.GetPoliciesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_casbin_policy_proto_init() }
func file_casbin_policy_proto_init() {
	if File_casbin_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_casbin_policy_proto_rawDesc), len(file_casbin_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_casbin_policy_proto_goTypes,
		DependencyIndexes: file_casbin_policy_proto_depIdxs,
		MessageInfos:      file_casbin_policy_proto_msgTypes,
	}.Build()
	File_casbin_policy_proto = out.File
	file_casbin_policy_proto_goTypes = nil
	file_casbin_policy_proto_depIdxs = nil
}
