// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: casbin_policy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CasbinPolicyService_GetPolicies_FullMethodName = "/casbin.CasbinPolicyService/GetPolicies"
)

// CasbinPolicyServiceClient is the client API for CasbinPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CasbinPolicyService 提供 Casbin 策略规则的 gRPC 查询服务
type CasbinPolicyServiceClient interface {
	// GetPolicies 获取指定租户的所有 Casbin 策略规则
	GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error)
}

type casbinPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCasbinPolicyServiceClient(cc grpc.ClientConnInterface) CasbinPolicyServiceClient {
	return &casbinPolicyServiceClient{cc}
}

func (c *casbinPolicyServiceClient) GetPolicies(ctx context.Context, in *GetPoliciesRequest, opts ...grpc.CallOption) (*GetPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoliciesResponse)
	err := c.cc.Invoke(ctx, CasbinPolicyService_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasbinPolicyServiceServer is the server API for CasbinPolicyService service.
// All implementations must embed UnimplementedCasbinPolicyServiceServer
// for forward compatibility.
//
// CasbinPolicyService 提供 Casbin 策略规则的 gRPC 查询服务
type CasbinPolicyServiceServer interface {
	// GetPolicies 获取指定租户的所有 Casbin 策略规则
	GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error)
	mustEmbedUnimplementedCasbinPolicyServiceServer()
}

// UnimplementedCasbinPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCasbinPolicyServiceServer struct{}

func (UnimplementedCasbinPolicyServiceServer) GetPolicies(context.Context, *GetPoliciesRequest) (*GetPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedCasbinPolicyServiceServer) mustEmbedUnimplementedCasbinPolicyServiceServer() {}
func (UnimplementedCasbinPolicyServiceServer) testEmbeddedByValue()                             {}

// UnsafeCasbinPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CasbinPolicyServiceServer will
// result in compilation errors.
type UnsafeCasbinPolicyServiceServer interface {
	mustEmbedUnimplementedCasbinPolicyServiceServer()
}

func RegisterCasbinPolicyServiceServer(s grpc.ServiceRegistrar, srv CasbinPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedCasbinPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CasbinPolicyService_ServiceDesc, srv)
}

func _CasbinPolicyService_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinPolicyServiceServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CasbinPolicyService_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinPolicyServiceServer).GetPolicies(ctx, req.(*GetPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CasbinPolicyService_ServiceDesc is the grpc.ServiceDesc for CasbinPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CasbinPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "casbin.CasbinPolicyService",
	HandlerType: (*CasbinPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicies",
			Handler:    _CasbinPolicyService_GetPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "casbin_policy.proto",
}
