// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: enforcement_type.proto

package enforcement_type

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnforcementTypeInfoService_GetEnforcementTypeById_FullMethodName   = "/enforcement_type.EnforcementTypeInfoService/GetEnforcementTypeById"
	EnforcementTypeInfoService_GetEnforcementTypeByCode_FullMethodName = "/enforcement_type.EnforcementTypeInfoService/GetEnforcementTypeByCode"
	EnforcementTypeInfoService_GetEnforcementTypeByName_FullMethodName = "/enforcement_type.EnforcementTypeInfoService/GetEnforcementTypeByName"
)

// EnforcementTypeInfoServiceClient is the client API for EnforcementTypeInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 执法类型信息服务
type EnforcementTypeInfoServiceClient interface {
	// 根据执法类型ID查询执法类型信息
	GetEnforcementTypeById(ctx context.Context, in *GetEnforcementTypeByIdReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error)
	// 根据执法类型编码查询执法类型信息
	GetEnforcementTypeByCode(ctx context.Context, in *GetEnforcementTypeByCodeReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error)
	// 根据执法类型名称查询执法类型信息
	GetEnforcementTypeByName(ctx context.Context, in *GetEnforcementTypeByNameReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error)
}

type enforcementTypeInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnforcementTypeInfoServiceClient(cc grpc.ClientConnInterface) EnforcementTypeInfoServiceClient {
	return &enforcementTypeInfoServiceClient{cc}
}

func (c *enforcementTypeInfoServiceClient) GetEnforcementTypeById(ctx context.Context, in *GetEnforcementTypeByIdReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnforcementTypeInfoReply)
	err := c.cc.Invoke(ctx, EnforcementTypeInfoService_GetEnforcementTypeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcementTypeInfoServiceClient) GetEnforcementTypeByCode(ctx context.Context, in *GetEnforcementTypeByCodeReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnforcementTypeInfoReply)
	err := c.cc.Invoke(ctx, EnforcementTypeInfoService_GetEnforcementTypeByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enforcementTypeInfoServiceClient) GetEnforcementTypeByName(ctx context.Context, in *GetEnforcementTypeByNameReq, opts ...grpc.CallOption) (*EnforcementTypeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnforcementTypeInfoReply)
	err := c.cc.Invoke(ctx, EnforcementTypeInfoService_GetEnforcementTypeByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnforcementTypeInfoServiceServer is the server API for EnforcementTypeInfoService service.
// All implementations must embed UnimplementedEnforcementTypeInfoServiceServer
// for forward compatibility.
//
// 执法类型信息服务
type EnforcementTypeInfoServiceServer interface {
	// 根据执法类型ID查询执法类型信息
	GetEnforcementTypeById(context.Context, *GetEnforcementTypeByIdReq) (*EnforcementTypeInfoReply, error)
	// 根据执法类型编码查询执法类型信息
	GetEnforcementTypeByCode(context.Context, *GetEnforcementTypeByCodeReq) (*EnforcementTypeInfoReply, error)
	// 根据执法类型名称查询执法类型信息
	GetEnforcementTypeByName(context.Context, *GetEnforcementTypeByNameReq) (*EnforcementTypeInfoReply, error)
	mustEmbedUnimplementedEnforcementTypeInfoServiceServer()
}

// UnimplementedEnforcementTypeInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnforcementTypeInfoServiceServer struct{}

func (UnimplementedEnforcementTypeInfoServiceServer) GetEnforcementTypeById(context.Context, *GetEnforcementTypeByIdReq) (*EnforcementTypeInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnforcementTypeById not implemented")
}
func (UnimplementedEnforcementTypeInfoServiceServer) GetEnforcementTypeByCode(context.Context, *GetEnforcementTypeByCodeReq) (*EnforcementTypeInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnforcementTypeByCode not implemented")
}
func (UnimplementedEnforcementTypeInfoServiceServer) GetEnforcementTypeByName(context.Context, *GetEnforcementTypeByNameReq) (*EnforcementTypeInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnforcementTypeByName not implemented")
}
func (UnimplementedEnforcementTypeInfoServiceServer) mustEmbedUnimplementedEnforcementTypeInfoServiceServer() {
}
func (UnimplementedEnforcementTypeInfoServiceServer) testEmbeddedByValue() {}

// UnsafeEnforcementTypeInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnforcementTypeInfoServiceServer will
// result in compilation errors.
type UnsafeEnforcementTypeInfoServiceServer interface {
	mustEmbedUnimplementedEnforcementTypeInfoServiceServer()
}

func RegisterEnforcementTypeInfoServiceServer(s grpc.ServiceRegistrar, srv EnforcementTypeInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedEnforcementTypeInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnforcementTypeInfoService_ServiceDesc, srv)
}

func _EnforcementTypeInfoService_GetEnforcementTypeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnforcementTypeByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnforcementTypeInfoService_GetEnforcementTypeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeById(ctx, req.(*GetEnforcementTypeByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnforcementTypeInfoService_GetEnforcementTypeByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnforcementTypeByCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnforcementTypeInfoService_GetEnforcementTypeByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeByCode(ctx, req.(*GetEnforcementTypeByCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnforcementTypeInfoService_GetEnforcementTypeByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnforcementTypeByNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnforcementTypeInfoService_GetEnforcementTypeByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnforcementTypeInfoServiceServer).GetEnforcementTypeByName(ctx, req.(*GetEnforcementTypeByNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EnforcementTypeInfoService_ServiceDesc is the grpc.ServiceDesc for EnforcementTypeInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnforcementTypeInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enforcement_type.EnforcementTypeInfoService",
	HandlerType: (*EnforcementTypeInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnforcementTypeById",
			Handler:    _EnforcementTypeInfoService_GetEnforcementTypeById_Handler,
		},
		{
			MethodName: "GetEnforcementTypeByCode",
			Handler:    _EnforcementTypeInfoService_GetEnforcementTypeByCode_Handler,
		},
		{
			MethodName: "GetEnforcementTypeByName",
			Handler:    _EnforcementTypeInfoService_GetEnforcementTypeByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enforcement_type.proto",
}
