// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: enforcement_type.proto

package enforcement_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据执法类型ID查询请求
type GetEnforcementTypeByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID，用于多租户系统
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                             // 执法类型唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnforcementTypeByIdReq) Reset() {
	*x = GetEnforcementTypeByIdReq{}
	mi := &file_enforcement_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnforcementTypeByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnforcementTypeByIdReq) ProtoMessage() {}

func (x *GetEnforcementTypeByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_enforcement_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnforcementTypeByIdReq.ProtoReflect.Descriptor instead.
func (*GetEnforcementTypeByIdReq) Descriptor() ([]byte, []int) {
	return file_enforcement_type_proto_rawDescGZIP(), []int{0}
}

func (x *GetEnforcementTypeByIdReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetEnforcementTypeByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 根据执法类型编码查询请求
type GetEnforcementTypeByCodeReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                   // 租户ID，用于多租户系统
	EnforcementTypeCode string                 `protobuf:"bytes,2,opt,name=enforcement_type_code,json=enforcementTypeCode,proto3" json:"enforcement_type_code,omitempty"` // 执法类型编码
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEnforcementTypeByCodeReq) Reset() {
	*x = GetEnforcementTypeByCodeReq{}
	mi := &file_enforcement_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnforcementTypeByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnforcementTypeByCodeReq) ProtoMessage() {}

func (x *GetEnforcementTypeByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_enforcement_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnforcementTypeByCodeReq.ProtoReflect.Descriptor instead.
func (*GetEnforcementTypeByCodeReq) Descriptor() ([]byte, []int) {
	return file_enforcement_type_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnforcementTypeByCodeReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetEnforcementTypeByCodeReq) GetEnforcementTypeCode() string {
	if x != nil {
		return x.EnforcementTypeCode
	}
	return ""
}

// 根据执法类型名称查询请求
type GetEnforcementTypeByNameReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                   // 租户ID，用于多租户系统
	EnforcementTypeName string                 `protobuf:"bytes,2,opt,name=enforcement_type_name,json=enforcementTypeName,proto3" json:"enforcement_type_name,omitempty"` // 执法类型名称
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetEnforcementTypeByNameReq) Reset() {
	*x = GetEnforcementTypeByNameReq{}
	mi := &file_enforcement_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnforcementTypeByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnforcementTypeByNameReq) ProtoMessage() {}

func (x *GetEnforcementTypeByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_enforcement_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnforcementTypeByNameReq.ProtoReflect.Descriptor instead.
func (*GetEnforcementTypeByNameReq) Descriptor() ([]byte, []int) {
	return file_enforcement_type_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnforcementTypeByNameReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetEnforcementTypeByNameReq) GetEnforcementTypeName() string {
	if x != nil {
		return x.EnforcementTypeName
	}
	return ""
}

// 执法类型信息响应，字段与领域模型SysEnforcementType对应
type EnforcementTypeInfoReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                               // 执法类型ID
	EnforcementTypeCode string                 `protobuf:"bytes,2,opt,name=enforcement_type_code,json=enforcementTypeCode,proto3" json:"enforcement_type_code,omitempty"` // 执法类型编码
	EnforcementTypeName string                 `protobuf:"bytes,3,opt,name=enforcement_type_name,json=enforcementTypeName,proto3" json:"enforcement_type_name,omitempty"` // 执法类型名称
	EnforcementTypeDesc string                 `protobuf:"bytes,4,opt,name=enforcement_type_desc,json=enforcementTypeDesc,proto3" json:"enforcement_type_desc,omitempty"` // 执法类型描述
	EnforcementTypePath string                 `protobuf:"bytes,5,opt,name=enforcement_type_path,json=enforcementTypePath,proto3" json:"enforcement_type_path,omitempty"` // 执法类型路径
	ParentId            int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`                                   // 父级ID
	Source              string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`                                                        // 来源
	Sort                int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`                                                           // 排序
	CreatedAt           string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                 // 创建时间
	UpdatedAt           string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                // 更新时间
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnforcementTypeInfoReply) Reset() {
	*x = EnforcementTypeInfoReply{}
	mi := &file_enforcement_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementTypeInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementTypeInfoReply) ProtoMessage() {}

func (x *EnforcementTypeInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_enforcement_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementTypeInfoReply.ProtoReflect.Descriptor instead.
func (*EnforcementTypeInfoReply) Descriptor() ([]byte, []int) {
	return file_enforcement_type_proto_rawDescGZIP(), []int{3}
}

func (x *EnforcementTypeInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnforcementTypeInfoReply) GetEnforcementTypeCode() string {
	if x != nil {
		return x.EnforcementTypeCode
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetEnforcementTypeName() string {
	if x != nil {
		return x.EnforcementTypeName
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetEnforcementTypeDesc() string {
	if x != nil {
		return x.EnforcementTypeDesc
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetEnforcementTypePath() string {
	if x != nil {
		return x.EnforcementTypePath
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *EnforcementTypeInfoReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *EnforcementTypeInfoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EnforcementTypeInfoReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_enforcement_type_proto protoreflect.FileDescriptor

const file_enforcement_type_proto_rawDesc = "" +
	"\n" +
	"\x16enforcement_type.proto\x12\x10enforcement_type\"H\n" +
	"\x19GetEnforcementTypeByIdReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"n\n" +
	"\x1bGetEnforcementTypeByCodeReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x122\n" +
	"\x15enforcement_type_code\x18\x02 \x01(\tR\x13enforcementTypeCode\"n\n" +
	"\x1bGetEnforcementTypeByNameReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x122\n" +
	"\x15enforcement_type_name\x18\x02 \x01(\tR\x13enforcementTypeName\"\x81\x03\n" +
	"\x18EnforcementTypeInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x122\n" +
	"\x15enforcement_type_code\x18\x02 \x01(\tR\x13enforcementTypeCode\x122\n" +
	"\x15enforcement_type_name\x18\x03 \x01(\tR\x13enforcementTypeName\x122\n" +
	"\x15enforcement_type_desc\x18\x04 \x01(\tR\x13enforcementTypeDesc\x122\n" +
	"\x15enforcement_type_path\x18\x05 \x01(\tR\x13enforcementTypePath\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt2\x83\x03\n" +
	"\x1aEnforcementTypeInfoService\x12s\n" +
	"\x16GetEnforcementTypeById\x12+.enforcement_type.GetEnforcementTypeByIdReq\x1a*.enforcement_type.EnforcementTypeInfoReply\"\x00\x12w\n" +
	"\x18GetEnforcementTypeByCode\x12-.enforcement_type.GetEnforcementTypeByCodeReq\x1a*.enforcement_type.EnforcementTypeInfoReply\"\x00\x12w\n" +
	"\x18GetEnforcementTypeByName\x12-.enforcement_type.GetEnforcementTypeByNameReq\x1a*.enforcement_type.EnforcementTypeInfoReply\"\x00BlZjjxt-evidence-system/evidence-management/shared/infrastructure/grpc/proto/enforcement_type;enforcement_typeb\x06proto3"

var (
	file_enforcement_type_proto_rawDescOnce sync.Once
	file_enforcement_type_proto_rawDescData []byte
)

func file_enforcement_type_proto_rawDescGZIP() []byte {
	file_enforcement_type_proto_rawDescOnce.Do(func() {
		file_enforcement_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enforcement_type_proto_rawDesc), len(file_enforcement_type_proto_rawDesc)))
	})
	return file_enforcement_type_proto_rawDescData
}

var file_enforcement_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_enforcement_type_proto_goTypes = []any{
	(*GetEnforcementTypeByIdReq)(nil),   // 0: enforcement_type.GetEnforcementTypeByIdReq
	(*GetEnforcementTypeByCodeReq)(nil), // 1: enforcement_type.GetEnforcementTypeByCodeReq
	(*GetEnforcementTypeByNameReq)(nil), // 2: enforcement_type.GetEnforcementTypeByNameReq
	(*EnforcementTypeInfoReply)(nil),    // 3: enforcement_type.EnforcementTypeInfoReply
}
var file_enforcement_type_proto_depIdxs = []int32{
	0, // 0: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeById:input_type -> enforcement_type.GetEnforcementTypeByIdReq
	1, // 1: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeByCode:input_type -> enforcement_type.GetEnforcementTypeByCodeReq
	2, // 2: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeByName:input_type -> enforcement_type.GetEnforcementTypeByNameReq
	3, // 3: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeById:output_type -> enforcement_type.EnforcementTypeInfoReply
	3, // 4: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeByCode:output_type -> enforcement_type.EnforcementTypeInfoReply
	3, // 5: enforcement_type.EnforcementTypeInfoService.GetEnforcementTypeByName:output_type -> enforcement_type.EnforcementTypeInfoReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enforcement_type_proto_init() }
func file_enforcement_type_proto_init() {
	if File_enforcement_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enforcement_type_proto_rawDesc), len(file_enforcement_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enforcement_type_proto_goTypes,
		DependencyIndexes: file_enforcement_type_proto_depIdxs,
		MessageInfos:      file_enforcement_type_proto_msgTypes,
	}.Build()
	File_enforcement_type_proto = out.File
	file_enforcement_type_proto_goTypes = nil
	file_enforcement_type_proto_depIdxs = nil
}
