// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: bwc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据执法记录仪ID查询请求
type GetBWCByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID，用于多租户系统
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`                             // 执法记录仪唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBWCByIdReq) Reset() {
	*x = GetBWCByIdReq{}
	mi := &file_bwc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBWCByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBWCByIdReq) ProtoMessage() {}

func (x *GetBWCByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBWCByIdReq.ProtoReflect.Descriptor instead.
func (*GetBWCByIdReq) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{0}
}

func (x *GetBWCByIdReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetBWCByIdReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 根据执法记录仪编号查询请求
type GetBWCByNoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户ID，用于多租户系统
	BwcNo         string                 `protobuf:"bytes,2,opt,name=bwc_no,json=bwcNo,proto3" json:"bwc_no,omitempty"`           // 执法记录仪编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBWCByNoReq) Reset() {
	*x = GetBWCByNoReq{}
	mi := &file_bwc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBWCByNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBWCByNoReq) ProtoMessage() {}

func (x *GetBWCByNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBWCByNoReq.ProtoReflect.Descriptor instead.
func (*GetBWCByNoReq) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{1}
}

func (x *GetBWCByNoReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetBWCByNoReq) GetBwcNo() string {
	if x != nil {
		return x.BwcNo
	}
	return ""
}

// 根据管理员ID查询执法记录仪列表请求
type GetBWCsByManagerIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // 租户ID，用于多租户系统
	ManagerId     int32                  `protobuf:"varint,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"` // 管理员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBWCsByManagerIdReq) Reset() {
	*x = GetBWCsByManagerIdReq{}
	mi := &file_bwc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBWCsByManagerIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBWCsByManagerIdReq) ProtoMessage() {}

func (x *GetBWCsByManagerIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBWCsByManagerIdReq.ProtoReflect.Descriptor instead.
func (*GetBWCsByManagerIdReq) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBWCsByManagerIdReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetBWCsByManagerIdReq) GetManagerId() int32 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

// 根据领用人ID查询执法记录仪列表请求
type GetBWCsByRequisitionerIdReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        int32                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                      // 租户ID，用于多租户系统
	RequisitionerId int32                  `protobuf:"varint,2,opt,name=requisitioner_id,json=requisitionerId,proto3" json:"requisitioner_id,omitempty"` // 领用人ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBWCsByRequisitionerIdReq) Reset() {
	*x = GetBWCsByRequisitionerIdReq{}
	mi := &file_bwc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBWCsByRequisitionerIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBWCsByRequisitionerIdReq) ProtoMessage() {}

func (x *GetBWCsByRequisitionerIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBWCsByRequisitionerIdReq.ProtoReflect.Descriptor instead.
func (*GetBWCsByRequisitionerIdReq) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{3}
}

func (x *GetBWCsByRequisitionerIdReq) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetBWCsByRequisitionerIdReq) GetRequisitionerId() int32 {
	if x != nil {
		return x.RequisitionerId
	}
	return 0
}

// 执法记录仪信息响应，字段与领域模型BodyWornCameraAggregate对应
type BWCInfoReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // 执法记录仪ID
	BwcNo              string                 `protobuf:"bytes,2,opt,name=bwc_no,json=bwcNo,proto3" json:"bwc_no,omitempty"`                                            // 执法记录仪编号
	BwcName            string                 `protobuf:"bytes,3,opt,name=bwc_name,json=bwcName,proto3" json:"bwc_name,omitempty"`                                      // 执法记录仪名称
	ManagerId          int32                  `protobuf:"varint,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`                               // 管理员ID
	ManagerOrgId       int32                  `protobuf:"varint,5,opt,name=manager_org_id,json=managerOrgId,proto3" json:"manager_org_id,omitempty"`                    // 管理员所在组织ID
	ManagerName        string                 `protobuf:"bytes,6,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`                          // 管理员名称
	ManagerOrgFullName string                 `protobuf:"bytes,7,opt,name=manager_org_full_name,json=managerOrgFullName,proto3" json:"manager_org_full_name,omitempty"` // 管理员所在组织全名称
	EnableUse          int32                  `protobuf:"varint,8,opt,name=enable_use,json=enableUse,proto3" json:"enable_use,omitempty"`                               // 是否能被使用：1:可用; 2:不可用
	Status             int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                                      // 状态：1:正常; 2:报废; 3:报修; 4:库存; 5:遗失
	Cpu                string                 `protobuf:"bytes,10,opt,name=cpu,proto3" json:"cpu,omitempty"`                                                            // CPU
	Memory             int32                  `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`                                                     // 内存，单位：G
	Disk               int32                  `protobuf:"varint,12,opt,name=disk,proto3" json:"disk,omitempty"`                                                         // 存储，单位：G
	NetworkCard        string                 `protobuf:"bytes,13,opt,name=network_card,json=networkCard,proto3" json:"network_card,omitempty"`                         // 网卡
	UsbNum             int32                  `protobuf:"varint,14,opt,name=usb_num,json=usbNum,proto3" json:"usb_num,omitempty"`                                       // USB数量
	System             string                 `protobuf:"bytes,15,opt,name=system,proto3" json:"system,omitempty"`                                                      // 操作系统
	Version            string                 `protobuf:"bytes,16,opt,name=version,proto3" json:"version,omitempty"`                                                    // 版本
	PurchaseTime       string                 `protobuf:"bytes,17,opt,name=purchase_time,json=purchaseTime,proto3" json:"purchase_time,omitempty"`                      // 购买时间
	Remark             string                 `protobuf:"bytes,18,opt,name=remark,proto3" json:"remark,omitempty"`                                                      // 备注
	RequisitionerId    int32                  `protobuf:"varint,19,opt,name=requisitioner_id,json=requisitionerId,proto3" json:"requisitioner_id,omitempty"`            // 领用人ID
	CreatedAt          string                 `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                               // 创建时间
	UpdatedAt          string                 `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                               // 更新时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BWCInfoReply) Reset() {
	*x = BWCInfoReply{}
	mi := &file_bwc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BWCInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BWCInfoReply) ProtoMessage() {}

func (x *BWCInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BWCInfoReply.ProtoReflect.Descriptor instead.
func (*BWCInfoReply) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{4}
}

func (x *BWCInfoReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BWCInfoReply) GetBwcNo() string {
	if x != nil {
		return x.BwcNo
	}
	return ""
}

func (x *BWCInfoReply) GetBwcName() string {
	if x != nil {
		return x.BwcName
	}
	return ""
}

func (x *BWCInfoReply) GetManagerId() int32 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *BWCInfoReply) GetManagerOrgId() int32 {
	if x != nil {
		return x.ManagerOrgId
	}
	return 0
}

func (x *BWCInfoReply) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *BWCInfoReply) GetManagerOrgFullName() string {
	if x != nil {
		return x.ManagerOrgFullName
	}
	return ""
}

func (x *BWCInfoReply) GetEnableUse() int32 {
	if x != nil {
		return x.EnableUse
	}
	return 0
}

func (x *BWCInfoReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BWCInfoReply) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *BWCInfoReply) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *BWCInfoReply) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *BWCInfoReply) GetNetworkCard() string {
	if x != nil {
		return x.NetworkCard
	}
	return ""
}

func (x *BWCInfoReply) GetUsbNum() int32 {
	if x != nil {
		return x.UsbNum
	}
	return 0
}

func (x *BWCInfoReply) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *BWCInfoReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BWCInfoReply) GetPurchaseTime() string {
	if x != nil {
		return x.PurchaseTime
	}
	return ""
}

func (x *BWCInfoReply) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BWCInfoReply) GetRequisitionerId() int32 {
	if x != nil {
		return x.RequisitionerId
	}
	return 0
}

func (x *BWCInfoReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BWCInfoReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 执法记录仪列表响应
type BWCListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bwcs          []*BWCInfoReply        `protobuf:"bytes,1,rep,name=bwcs,proto3" json:"bwcs,omitempty"`    // 执法记录仪列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BWCListReply) Reset() {
	*x = BWCListReply{}
	mi := &file_bwc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BWCListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BWCListReply) ProtoMessage() {}

func (x *BWCListReply) ProtoReflect() protoreflect.Message {
	mi := &file_bwc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BWCListReply.ProtoReflect.Descriptor instead.
func (*BWCListReply) Descriptor() ([]byte, []int) {
	return file_bwc_proto_rawDescGZIP(), []int{5}
}

func (x *BWCListReply) GetBwcs() []*BWCInfoReply {
	if x != nil {
		return x.Bwcs
	}
	return nil
}

func (x *BWCListReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_bwc_proto protoreflect.FileDescriptor

const file_bwc_proto_rawDesc = "" +
	"\n" +
	"\tbwc.proto\x12\x03bwc\"<\n" +
	"\rGetBWCByIdReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"C\n" +
	"\rGetBWCByNoReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12\x15\n" +
	"\x06bwc_no\x18\x02 \x01(\tR\x05bwcNo\"S\n" +
	"\x15GetBWCsByManagerIdReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\x05R\tmanagerId\"e\n" +
	"\x1bGetBWCsByRequisitionerIdReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x05R\btenantId\x12)\n" +
	"\x10requisitioner_id\x18\x02 \x01(\x05R\x0frequisitionerId\"\xf4\x04\n" +
	"\fBWCInfoReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x15\n" +
	"\x06bwc_no\x18\x02 \x01(\tR\x05bwcNo\x12\x19\n" +
	"\bbwc_name\x18\x03 \x01(\tR\abwcName\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\x05R\tmanagerId\x12$\n" +
	"\x0emanager_org_id\x18\x05 \x01(\x05R\fmanagerOrgId\x12!\n" +
	"\fmanager_name\x18\x06 \x01(\tR\vmanagerName\x121\n" +
	"\x15manager_org_full_name\x18\a \x01(\tR\x12managerOrgFullName\x12\x1d\n" +
	"\n" +
	"enable_use\x18\b \x01(\x05R\tenableUse\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x10\n" +
	"\x03cpu\x18\n" +
	" \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\v \x01(\x05R\x06memory\x12\x12\n" +
	"\x04disk\x18\f \x01(\x05R\x04disk\x12!\n" +
	"\fnetwork_card\x18\r \x01(\tR\vnetworkCard\x12\x17\n" +
	"\ausb_num\x18\x0e \x01(\x05R\x06usbNum\x12\x16\n" +
	"\x06system\x18\x0f \x01(\tR\x06system\x12\x18\n" +
	"\aversion\x18\x10 \x01(\tR\aversion\x12#\n" +
	"\rpurchase_time\x18\x11 \x01(\tR\fpurchaseTime\x12\x16\n" +
	"\x06remark\x18\x12 \x01(\tR\x06remark\x12)\n" +
	"\x10requisitioner_id\x18\x13 \x01(\x05R\x0frequisitionerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\tR\tupdatedAt\"K\n" +
	"\fBWCListReply\x12%\n" +
	"\x04bwcs\x18\x01 \x03(\v2\x11.bwc.BWCInfoReplyR\x04bwcs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x98\x02\n" +
	"\x0eBWCInfoService\x125\n" +
	"\n" +
	"GetBWCById\x12\x12.bwc.GetBWCByIdReq\x1a\x11.bwc.BWCInfoReply\"\x00\x125\n" +
	"\n" +
	"GetBWCByNo\x12\x12.bwc.GetBWCByNoReq\x1a\x11.bwc.BWCInfoReply\"\x00\x12E\n" +
	"\x12GetBWCsByManagerId\x12\x1a.bwc.GetBWCsByManagerIdReq\x1a\x11.bwc.BWCListReply\"\x00\x12Q\n" +
	"\x18GetBWCsByRequisitionerId\x12 .bwc.GetBWCsByRequisitionerIdReq\x1a\x11.bwc.BWCListReply\"\x00B]Z[jxt-evidence-system/security-management/equipment_management/interface/grpc/bwc/proto;protob\x06proto3"

var (
	file_bwc_proto_rawDescOnce sync.Once
	file_bwc_proto_rawDescData []byte
)

func file_bwc_proto_rawDescGZIP() []byte {
	file_bwc_proto_rawDescOnce.Do(func() {
		file_bwc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bwc_proto_rawDesc), len(file_bwc_proto_rawDesc)))
	})
	return file_bwc_proto_rawDescData
}

var file_bwc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bwc_proto_goTypes = []any{
	(*GetBWCByIdReq)(nil),               // 0: bwc.GetBWCByIdReq
	(*GetBWCByNoReq)(nil),               // 1: bwc.GetBWCByNoReq
	(*GetBWCsByManagerIdReq)(nil),       // 2: bwc.GetBWCsByManagerIdReq
	(*GetBWCsByRequisitionerIdReq)(nil), // 3: bwc.GetBWCsByRequisitionerIdReq
	(*BWCInfoReply)(nil),                // 4: bwc.BWCInfoReply
	(*BWCListReply)(nil),                // 5: bwc.BWCListReply
}
var file_bwc_proto_depIdxs = []int32{
	4, // 0: bwc.BWCListReply.bwcs:type_name -> bwc.BWCInfoReply
	0, // 1: bwc.BWCInfoService.GetBWCById:input_type -> bwc.GetBWCByIdReq
	1, // 2: bwc.BWCInfoService.GetBWCByNo:input_type -> bwc.GetBWCByNoReq
	2, // 3: bwc.BWCInfoService.GetBWCsByManagerId:input_type -> bwc.GetBWCsByManagerIdReq
	3, // 4: bwc.BWCInfoService.GetBWCsByRequisitionerId:input_type -> bwc.GetBWCsByRequisitionerIdReq
	4, // 5: bwc.BWCInfoService.GetBWCById:output_type -> bwc.BWCInfoReply
	4, // 6: bwc.BWCInfoService.GetBWCByNo:output_type -> bwc.BWCInfoReply
	5, // 7: bwc.BWCInfoService.GetBWCsByManagerId:output_type -> bwc.BWCListReply
	5, // 8: bwc.BWCInfoService.GetBWCsByRequisitionerId:output_type -> bwc.BWCListReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bwc_proto_init() }
func file_bwc_proto_init() {
	if File_bwc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bwc_proto_rawDesc), len(file_bwc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bwc_proto_goTypes,
		DependencyIndexes: file_bwc_proto_depIdxs,
		MessageInfos:      file_bwc_proto_msgTypes,
	}.Build()
	File_bwc_proto = out.File
	file_bwc_proto_goTypes = nil
	file_bwc_proto_depIdxs = nil
}
