// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: bwc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BWCInfoService_GetBWCById_FullMethodName               = "/bwc.BWCInfoService/GetBWCById"
	BWCInfoService_GetBWCByNo_FullMethodName               = "/bwc.BWCInfoService/GetBWCByNo"
	BWCInfoService_GetBWCsByManagerId_FullMethodName       = "/bwc.BWCInfoService/GetBWCsByManagerId"
	BWCInfoService_GetBWCsByRequisitionerId_FullMethodName = "/bwc.BWCInfoService/GetBWCsByRequisitionerId"
)

// BWCInfoServiceClient is the client API for BWCInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 执法记录仪信息服务
type BWCInfoServiceClient interface {
	// 根据执法记录仪ID查询信息
	GetBWCById(ctx context.Context, in *GetBWCByIdReq, opts ...grpc.CallOption) (*BWCInfoReply, error)
	// 根据执法记录仪编号查询信息
	GetBWCByNo(ctx context.Context, in *GetBWCByNoReq, opts ...grpc.CallOption) (*BWCInfoReply, error)
	// 根据管理员ID查询执法记录仪列表
	GetBWCsByManagerId(ctx context.Context, in *GetBWCsByManagerIdReq, opts ...grpc.CallOption) (*BWCListReply, error)
	// 根据领用人ID查询执法记录仪列表
	GetBWCsByRequisitionerId(ctx context.Context, in *GetBWCsByRequisitionerIdReq, opts ...grpc.CallOption) (*BWCListReply, error)
}

type bWCInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBWCInfoServiceClient(cc grpc.ClientConnInterface) BWCInfoServiceClient {
	return &bWCInfoServiceClient{cc}
}

func (c *bWCInfoServiceClient) GetBWCById(ctx context.Context, in *GetBWCByIdReq, opts ...grpc.CallOption) (*BWCInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BWCInfoReply)
	err := c.cc.Invoke(ctx, BWCInfoService_GetBWCById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bWCInfoServiceClient) GetBWCByNo(ctx context.Context, in *GetBWCByNoReq, opts ...grpc.CallOption) (*BWCInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BWCInfoReply)
	err := c.cc.Invoke(ctx, BWCInfoService_GetBWCByNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bWCInfoServiceClient) GetBWCsByManagerId(ctx context.Context, in *GetBWCsByManagerIdReq, opts ...grpc.CallOption) (*BWCListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BWCListReply)
	err := c.cc.Invoke(ctx, BWCInfoService_GetBWCsByManagerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bWCInfoServiceClient) GetBWCsByRequisitionerId(ctx context.Context, in *GetBWCsByRequisitionerIdReq, opts ...grpc.CallOption) (*BWCListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BWCListReply)
	err := c.cc.Invoke(ctx, BWCInfoService_GetBWCsByRequisitionerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BWCInfoServiceServer is the server API for BWCInfoService service.
// All implementations must embed UnimplementedBWCInfoServiceServer
// for forward compatibility.
//
// 执法记录仪信息服务
type BWCInfoServiceServer interface {
	// 根据执法记录仪ID查询信息
	GetBWCById(context.Context, *GetBWCByIdReq) (*BWCInfoReply, error)
	// 根据执法记录仪编号查询信息
	GetBWCByNo(context.Context, *GetBWCByNoReq) (*BWCInfoReply, error)
	// 根据管理员ID查询执法记录仪列表
	GetBWCsByManagerId(context.Context, *GetBWCsByManagerIdReq) (*BWCListReply, error)
	// 根据领用人ID查询执法记录仪列表
	GetBWCsByRequisitionerId(context.Context, *GetBWCsByRequisitionerIdReq) (*BWCListReply, error)
	mustEmbedUnimplementedBWCInfoServiceServer()
}

// UnimplementedBWCInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBWCInfoServiceServer struct{}

func (UnimplementedBWCInfoServiceServer) GetBWCById(context.Context, *GetBWCByIdReq) (*BWCInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBWCById not implemented")
}
func (UnimplementedBWCInfoServiceServer) GetBWCByNo(context.Context, *GetBWCByNoReq) (*BWCInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBWCByNo not implemented")
}
func (UnimplementedBWCInfoServiceServer) GetBWCsByManagerId(context.Context, *GetBWCsByManagerIdReq) (*BWCListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBWCsByManagerId not implemented")
}
func (UnimplementedBWCInfoServiceServer) GetBWCsByRequisitionerId(context.Context, *GetBWCsByRequisitionerIdReq) (*BWCListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBWCsByRequisitionerId not implemented")
}
func (UnimplementedBWCInfoServiceServer) mustEmbedUnimplementedBWCInfoServiceServer() {}
func (UnimplementedBWCInfoServiceServer) testEmbeddedByValue()                        {}

// UnsafeBWCInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BWCInfoServiceServer will
// result in compilation errors.
type UnsafeBWCInfoServiceServer interface {
	mustEmbedUnimplementedBWCInfoServiceServer()
}

func RegisterBWCInfoServiceServer(s grpc.ServiceRegistrar, srv BWCInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedBWCInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BWCInfoService_ServiceDesc, srv)
}

func _BWCInfoService_GetBWCById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBWCByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BWCInfoServiceServer).GetBWCById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BWCInfoService_GetBWCById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BWCInfoServiceServer).GetBWCById(ctx, req.(*GetBWCByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BWCInfoService_GetBWCByNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBWCByNoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BWCInfoServiceServer).GetBWCByNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BWCInfoService_GetBWCByNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BWCInfoServiceServer).GetBWCByNo(ctx, req.(*GetBWCByNoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BWCInfoService_GetBWCsByManagerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBWCsByManagerIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BWCInfoServiceServer).GetBWCsByManagerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BWCInfoService_GetBWCsByManagerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BWCInfoServiceServer).GetBWCsByManagerId(ctx, req.(*GetBWCsByManagerIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BWCInfoService_GetBWCsByRequisitionerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBWCsByRequisitionerIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BWCInfoServiceServer).GetBWCsByRequisitionerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BWCInfoService_GetBWCsByRequisitionerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BWCInfoServiceServer).GetBWCsByRequisitionerId(ctx, req.(*GetBWCsByRequisitionerIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BWCInfoService_ServiceDesc is the grpc.ServiceDesc for BWCInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BWCInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bwc.BWCInfoService",
	HandlerType: (*BWCInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBWCById",
			Handler:    _BWCInfoService_GetBWCById_Handler,
		},
		{
			MethodName: "GetBWCByNo",
			Handler:    _BWCInfoService_GetBWCByNo_Handler,
		},
		{
			MethodName: "GetBWCsByManagerId",
			Handler:    _BWCInfoService_GetBWCsByManagerId_Handler,
		},
		{
			MethodName: "GetBWCsByRequisitionerId",
			Handler:    _BWCInfoService_GetBWCsByRequisitionerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bwc.proto",
}
